### PR TITLE
fix: Helmholtz AAI handling if only one eduperson_entitlement is returned

### LINKED ISSUE #857: Helmholtz AAI: ClassCastException when retrieving claims
In this line:

https://github.com/research-software-directory/RSD-as-a-service/blob/956a9c7805c25c7c013acfa2db8f55abf071b5e5/authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java#L198

`getClaim()` returns an array if multiple claims exist. If only one claim exists, it returns a String instead. In this case, the casting to JSONArray doesn't work anymore and a `ClassCastException` is thrown.

### PR DESCRIPTION
**Pull request by cmeessen**
# Fix issue in Helmholtz AAI login

Fixes #857 

Changes proposed in this pull request:

* fixes handling of `eduperson_entitlement`
* adds an allow list for Helmholtz AAI via env variable `HELMHOLTZAAI_ALLOW_LIST`
* users in allow list are identified via email address
* enable usage of allow list via `HELMHOLTZAAI_USE_ALLOW_LIST`
* enable external debugging in auth container

How to test:

* enable Helmholtz AAI login provider and in `.env` set
  * `HELMHOLTZAAI_ALLOW_EXTERNAL_USERS=false`
  * `HELMHOLTZAAI_USE_ALLOW_LIST=false`
* `docker compose build --parallel && docker compose up --scale scrapers=0`
* login via Helmholtz AAI using a social IdP (Google, ORCID or GitHub)
* check that auth does not log any errors
* the user will be presented the error message: "You are not allowed to login."
* `docker compose stop`
* in `.env` set `HELMHOLTZAAI_USE_ALLOW_LIST=true`
* `docker compose up --scale scrapers=0`
* login via Helmholtz AAI using a social IdP (Google, ORCID or GitHub)
* the user will be presented the error message: "Your email address (<mail>) is not in the allow list."
* `docker compose stop`
* in `.env` add your mail address to `HELMHOLTZAAI_ALLOW_LIST`
* `docker compose up --scale scrapers=0`
* login via Helmholtz AAI using the same social idp as before
* login successful

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [x] Link to a GitHub issue
*   [ ] Update documentation
*   [x] Tests

### CODE REVIEW

**Review by dmijatovic — APPROVED** [review]
It works as described.

File: authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java [hunk 1]
```diff
@@ -195,7 +195,13 @@ public OpenIdInfo openidInfo() {
 			throw new RuntimeException(e);
 		}
 
-		JSONArray entitlements = (JSONArray) userInfo.getClaim("eduperson_entitlement");
+		JSONArray entitlements = new JSONArray();
+		try {
```
Comment (ewan-escience) [inline authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java:199]: It would be better to test if it is a `JSONArray` with `instanceof`, e.g.
```java
Object edupersonClaim = userInfo.getClaim("eduperson_entitlement");
if (edupersonClaim instanceof JSONArray) {
// do something
}
```

**Review by ewan-escience — CHANGES_REQUESTED** [review]
A small code practice request.

File: authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java (hunk 1 above)
Comment (cmeessen) [reply authentication/src/main/java/nl/esciencecenter/rsd/authentication/HelmholtzAaiLogin.java]: Done

**Review by ewan-escience — APPROVED** [review]
