### PR TITLE
fix: update contact people when new contact person is set

### LINKED ISSUE #948: It is possible to make contact person to more than one member in projects
To change the contact person of a project, you have to first change the current contact person. 
I would expect that the new contact person switch will disable the previous one by default.
When selecting a new contact person there is no indication or information that now there are 2 contact persons, and it is unsure which one is selected.

To fix: 
- when selecting a contact person, disable the rest in that operation, leaving the new contact person as the only enabled option.

### PR DESCRIPTION
**Pull request by ewan-escience**
## Prevent multiple contact people

Changes proposed in this pull request:

* When a contributor or team member is made to be a contact person, the other contributors/team members are set *not* to be a contact person

How to test:

* `docker compose down --volumes && docker compose build --parallel && docker compose up --scale data-generation=1`
* Sign in as admin, edit a software contributor to be a contact person, the other contributors should not be a contact person anymore
* Repeat when adding a new contributor
* Try the same for the team members of a project

Closes #948

PR Checklist:

* [ ] Increase version numbers in `docker-compose.yml`
* [x] Link to a GitHub issue
* [ ] Update documentation
* [ ] Tests

### CODE REVIEW

File: frontend/components/projects/edit/team/index.tsx [hunk 1]
```diff
@@ -75,17 +75,33 @@ export default function ProjectTeam() {
...
+      updateContactPeople(member, newMembersList)
       setMembers(newMembersList)
     }
   }
 
+  async function updateContactPeople(data: TeamMember, list: TeamMember[]) {
+    if (!data.is_contact_person) return
+
+    list.forEach(person => {
+      if (!person.is_contact_person || person === data) return
```
Comment (dmijatovic) [inline frontend/components/projects/edit/team/index.tsx:95]: Does person === data works properly? In JS this compares the reference (ids) of these object and not the content, so it never be equal ASFAIK.

File: frontend/components/projects/edit/team/index.tsx [hunk 2]
```diff
@@ -75,17 +75,33 @@ export default function ProjectTeam() {
...
       const newMembersList = [
         ...members,
         member
       ]
+      updateContactPeople(member, newMembersList)
       setMembers(newMembersList)
     }
   }
 
+  async function updateContactPeople(data: TeamMember, list: TeamMember[]) {
```
Comment (dmijatovic) [inline frontend/components/projects/edit/team/index.tsx:91]: I would prefer if the api call function is in the same file where other api calls of team section are.

File: frontend/components/projects/edit/team/index.tsx (hunk 1 above)
Comment (ewan-escience) [reply frontend/components/projects/edit/team/index.tsx:95]: Yes, it works, because data was added to the list just before in the calling function.

**Review by dmijatovic — APPROVED** [review]
Interesting approach :-). I thinks we can close #1004 too with this (for now)
