### PR TITLE
Mention feedback

### LINKED ISSUE #745: Feedback about adding mention via DOI
Got some feedback from Ben: 

He was trying to add the following mention by pasting into the RSD: 

https://doi.ieeecomputersociety.org/10.1109/PMBS56514.2022.00010

This failed to find the paper, as we detect the "https://doi.org/" prefix, but no the "https://doi.ieeecomputersociety.org/" one. Apparently IEEE has it's own DOI resolver?

### LINKED ISSUE #786: Bulk import mentions
Add the possibility to bulk import mentions by DOI from e.g. a line separated file.

### LINKED ISSUE #795: search by title with extra spaces problem
Using title to find the DOI is quite helpful, specially for the old end reports that do not put DOIs. However, if the title contains extra spaces, RSD is unable to find the existing record.
For example, 
`Automatic extraction of  ingredient's substitutes` vs `Automatic extraction of ingredient's substitutes`

Removing extra spaces solves the problem, but is hard to see the issue if you have a small font size.

### PR DESCRIPTION
**Pull request by ewan-escience**
# Various mention improvements

Changes proposed in this pull request:

* When a search term contains a DOI anywhere (URL or not), it is detected and we will search on that DOI only (#745)
* Bulk import of mentions with a DOI, up to 75 a time (#786)
* Remove double spaces when searching for a mention title (#795)

How to test:

* `docker-compose down --volumes && docker-compose build --parallel && docker-compose up --scale data-generation=0`.
* Login, create a software page, go to mentions and add the following list:
```
https://doi.ieeecomputersociety.org/10.1109/PMBS56514.2022.00010
10.5281/zenodo.3734289doesnotexist
not a DOI
   10.5281/zenodo.3734289   
   10.5281/zenodo.5604609
10.1016/j.sleep.2019.02.008   
10.2139/ssrn.4090562
10.1109/eScience.2016.7870882
10.3389/fmars.2021.667591
10.5281/zenodo.3993242
10.1007/10704282_88
10.5281/zenodo.5788657
10.4233/uuid:4bb38399-9267-428f-b10a-80b86e101f23
10.5281/zenodo.3970975
10.1145/3514197.3551252
10.1016/j.dsr.2020.103427
10.5888/pcd16.180200
10.5281/zenodo.7524315
10.1007/s00198-019-04862-6
10.5281/zenodo.4274773
10.5281/zenodo.46572
10.5281/zenodo.58372
10.5281/zenodo.6010407
10.1088/1748-9326/ac5cf4
10.5281/zenodo.1168441
10.5281/zenodo.4017909
10.5281/zenodo.7274246
10.5281/zenodo.1045194
10.5281/zenodo.7274494
10.1007/s42001-021-00145-5
10.3390/children5100137
10.5281/zenodo.1305971
10.5281/zenodo.4290717
10.5281/zenodo.3686602
10.5281/zenodo.4293357
10.5281/zenodo.4027119
10.5281/zenodo.7010595
10.1103/physrevfluids.7.034501
10.5281/zenodo.4525749
10.5281/zenodo.7277738
10.5281/zenodo.3902723
10.5281/zenodo.7096809
10.5281/zenodo.7111441
10.5194/esd-11-751-2020
10.1016/j.ijmultiphaseflow.2022.104153
10.5281/zenodo.1135095
10.1038/nmeth.3959
10.1128/mSystems.00937-21
10.5281/zenodo.5842611
10.5281/zenodo.7150823
10.5281/zenodo.4242056
10.5281/zenodo.581179
10.5281/zenodo.823562
10.5281/zenodo.4584626
10.5281/zenodo.47144
10.1016/j.marpolbul.2018.09.019
10.5281/zenodo.997294
10.5281/zenodo.5800123
10.1016/j.jcp.2020.109979
10.5281/zenodo.5809671
10.5281/zenodo.47325
10.5281/zenodo.6821889
10.5281/zenodo.5957173
10.5281/zenodo.6344841
10.5281/zenodo.3829891
10.5281/zenodo.1168379
10.5281/zenodo.321917
10.5281/zenodo.572818
10.5281/zenodo.838671
10.5281/zenodo.7646708
10.5281/zenodo.5725301
10.5281/zenodo.2635591
10.4208/cicp.oa-2021-0182
```
This list contains 71 valid DOIs (of which one URL, some with extra white space surrounding the DOI), one DOI that does not exist and one line that does not contain a DOI. The wrong lines should generate an error. You can also disable adding some mentions after inspecting them.
* Create a project page and add the following 75 DataCite mentions as *impact*:
```
10.5281/zenodo.1429520
10.5281/zenodo.3244998
10.5281/zenodo.3383755
10.5281/zenodo.7421802
10.5281/zenodo.5864811
10.5281/zenodo.1420142
10.5281/zenodo.4679406
10.5281/zenodo.2638710
10.5281/zenodo.7015183
10.5281/zenodo.1219840
10.5281/zenodo.2639286
10.5281/zenodo.1435005
10.5281/zenodo.7746407
10.5281/zenodo.996374
10.5281/zenodo.1318953
10.5281/zenodo.3678631
10.5281/zenodo.4059590
10.5281/zenodo.7430545
10.5281/zenodo.5506884
10.5281/zenodo.7712054
10.5281/zenodo.1174017
10.5281/zenodo.2156236
10.5281/zenodo.5196084
10.5281/zenodo.5146351
10.5281/zenodo.1065436
10.5281/zenodo.7211883
10.5281/zenodo.7707606
10.5281/zenodo.7043054
10.5281/zenodo.6619933
10.5281/zenodo.4311332
10.5281/zenodo.6704011
10.5281/zenodo.1443228
10.5281/zenodo.854679
10.5281/zenodo.7387004
10.5281/zenodo.4055954
10.5281/zenodo.7687471
10.5281/zenodo.3873089
10.5281/zenodo.5873399
10.5281/zenodo.1050358
10.5281/zenodo.5068521
10.5281/zenodo.5534586
10.5281/zenodo.7680187
10.5281/zenodo.1443236
10.5281/zenodo.7055787
10.5281/zenodo.5638044
10.5281/zenodo.7275833
10.5281/zenodo.60929
10.5281/zenodo.6617131
10.5281/zenodo.6380951
10.5281/zenodo.7669373
10.5281/zenodo.1050359
10.5281/zenodo.1129323
10.5281/zenodo.7760575
10.5281/zenodo.910906
10.5281/zenodo.1308781
10.5281/zenodo.5790782
10.5281/zenodo.5790783
10.5281/zenodo.1064674
10.5281/zenodo.3813612
10.5281/zenodo.1064599
10.5281/zenodo.1175883
10.5281/zenodo.50388
10.5281/zenodo.4679411
10.5281/zenodo.5128614
10.5281/zenodo.3964548
10.5281/zenodo.5179931
10.5281/zenodo.23391
10.5281/zenodo.51692
10.5281/zenodo.1506510
10.5281/zenodo.5113904
10.5281/zenodo.13559
10.5281/zenodo.4201949
10.5281/zenodo.4770035
10.5281/zenodo.7685495
10.5281/zenodo.1402677
```
* Add the following 75 Crossref mentions as *output*:
```
10.1093/mnras/stx2721
10.1016/j.future.2018.12.026
10.1016/j.atherosclerosis.2015.09.005
10.1021/jacsau.1c00228
10.1021/acs.jcim.6b00686
10.1002/essoar.10501325.1
10.21105/joss.02411
10.5194/esd-12-253-2021
10.1117/12.2547459
10.1615/int.j.uncertaintyquantification.2022039993
10.1007/s00592-018-1161-8
10.1051/0004-6361/201732020
10.3390/jcm8071053
10.5117/ccr2022.2.007.hage
10.1093/nar/gkv303
10.1029/2021ms002892
10.1186/s13063-018-3067-8
10.1186/s13063-018-2923-x
10.3390/metabo12010087
10.1117/12.2608611
10.1111/tgis.12855
10.1145/3520304.3533995
10.1021/acs.analchem.8b05112
10.1145/3449639.3459306
10.1109/aciiw.2019.8925059
10.1111/tgis.12692
10.1175/jas-d-15-0215.1
10.21105/joss.04494
10.1103/physreve.99.043309
10.12688/f1000research.54159.1
10.5194/egusphere-egu23-9026
10.1145/3453141
10.1038/s41598-019-46771-y
10.1039/D1NP00023C
10.1038/s41589-021-00949-6
10.1007/978-3-030-22747-0_20
10.1002/qj.4401
10.1038/s41467-021-22616-z
10.1016/j.buildenv.2020.107109
10.5194/egusphere-egu23-13859
10.1017/S0033291717000186
10.1186/s12887-018-1301-x
10.5194/ems2022-407
10.1111/tgis.12939
10.3390/ijgi11120629
10.5194/esd-11-1233-2020
10.1007/s11332-019-00527-3
10.1098/rsta.2020.0221
10.1186/s13321-022-00656-x
10.1186/1471-2105-9-399
10.1016/j.apsusc.2020.148836
10.1016/j.phanu.2013.11.027
10.1145/2996913.2997005
10.1029/2021jc017372
10.1093/nar/gkr310
10.1093/bioinformatics/btac596
10.1016/j.softx.2020.100626
10.1145/3460210.3493559
10.1007/s00500-020-05243-6
10.1186/s13321-021-00529-9
10.1186/s13321-022-00620-9
10.7717/peerj.13712
10.1021/acs.biochem.9b00735
10.1021/acs.jctc.0c00147
10.1109/pmbs56514.2022.00010
10.1109/access.2021.3113892
10.1016/j.ygeno.2022.110280
10.1088/1742-6596/1525/1/012041
10.1021/acs.iecr.0c05845
10.1016/S1474-4422(18)30203-5
10.3897/rio.5.e35820
10.1109/eScience.2018.00069
10.1111/fog.12596
10.1186/s13321-021-00485-4
10.18174/551416
```
* Play around with the functionality a bit more
* Add a single mention by searching for the following title (which contains a double space): `Automatic extraction of  ingredient's substitutes`. A result should be found.

Closes #745
Closes #786
Closes #795

PR Checklist:

*   [ ] Increase version numbers in `docker-compose.yml`
*   [X] Link to a GitHub issue
*   [ ] Update documentation
*   [ ] Tests

### CODE REVIEW

File: frontend/components/mention/BulkImport.tsx [hunk 1]
```diff
@@ -0,0 +1,312 @@
...
+            </DialogTitle>
+            <DialogContent>
+              <List>
+                {Array.from(searchResults.keys()).map(doi => {
+                  const result = searchResults.get(doi)!
+                  if (result?.status === 'valid') {
+                    const mention = searchResults.get(doi)?.mention!
+                    return (
+                      <ListItem key = {doi}>
+                        <ListItemText primary={`${doi}: ${mention.title}, ${mention.authors}, ${result.source}`}></ListItemText>
```
Comment (dmijatovic) [inline frontend/components/mention/BulkImport.tsx:285]: I think it would look more clear if we put DOI only as primary input and the title and source as secondary. I am not sure about autors because it could be a long list (or we could cap it to 1 line max?)

File: frontend/components/mention/BulkImport.tsx [hunk 2]
```diff
@@ -0,0 +1,312 @@
...
+                        <Switch defaultChecked={result.include} onChange={() => {result.include = !result.include}} />
+                      </ListItem>
+                    )
+                  } else {
+                    return (
+                      <ListItem key = {doi}>
```
Comment (dmijatovic) [inline frontend/components/mention/BulkImport.tsx:291]: I would shouw these in similar way. Doi entry as primary text, error message as secondary text with className="text-error".

File: frontend/components/mention/BulkImport.tsx [hunk 3]
```diff
@@ -0,0 +1,312 @@
...
+    setSubmitEnabled(true)
+  }
+
+
+	return (
+    <>
+        <Button onClick={() => setDialogOpen(true)}>
+          Bulk add mentions
+        </Button>
+        <Dialog maxWidth='md' sx={{minWidth: '40rem'}} open={dialogOpen} onClose={() => closeDialog()}>
```
Comment (dmijatovic) [inline frontend/components/mention/BulkImport.tsx:255]: Please add the following styles to sx to fix dialog size.
```Javascript
sx={{
      '.MuiPaper-root': {
        width: smallScreen ? 'auto':'50vw',
        height: smallScreen ? 'auto':'50vh',
    }
  }}
```

File: frontend/components/mention/BulkImport.tsx [hunk 4]
```diff
@@ -0,0 +1,312 @@
...
+import ListItem from '@mui/material/ListItem'
+import ListItemText from '@mui/material/ListItemText'
+import Switch from '@mui/material/Switch'
+import {createJsonHeaders} from '~/utils/fetchHelpers'
+import useSnackbar from '~/components/snackbar/useSnackbar'
+import DialogContent from '@mui/material/DialogContent'
+import DialogActions from '@mui/material/DialogActions'
+
+export default function BulkImport({table, entityId}: {table: 'mention_for_software' | 'output_for_project' | 'impact_for_project', entityId: string}) {
+	const [dialogOpen, setDialogOpen] = useState<boolean>(false)
```
Comment (dmijatovic) [inline frontend/components/mention/BulkImport.tsx:26]: Can you add this screen size hook to enable full screen modal on mobile devices?
```Javascript
const smallScreen = useMediaQuery('(max-width:768px)')
```

File: frontend/components/mention/BulkImport.tsx [hunk 5]
```diff
@@ -0,0 +1,312 @@
...
+              Results
+            </DialogTitle>
+            <DialogContent>
+              <List>
+                {Array.from(searchResults.keys()).map(doi => {
+                  const result = searchResults.get(doi)!
+                  if (result?.status === 'valid') {
+                    const mention = searchResults.get(doi)?.mention!
+                    return (
+                      <ListItem key = {doi}>
```
Comment (dmijatovic) [inline frontend/components/mention/BulkImport.tsx:284]: ListItem component has designated place for action buttons. Maybe add switch to it?

```Javascript
<ListItem
  key={doi}
  secondaryAction={
    <Switch
      disabled={result?.status !== 'valid'}
      defaultChecked={result.include}
      onChange={() => { result.include = !result.include }}
    />
  }
  sx={{
    paddingRight:'5rem',
    '&:hover': {
      backgroundColor:'grey.100'
    },
  }}
>
```

File: frontend/components/software/edit/mentions/utils.ts [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+  try {
+    new URL(query)
+    return {term: query, type: 'url'}
+  } catch (error: any) {
+    if (error.constructor.name === 'TypeError') {
+      // remove double spaces:
+      query = query.replaceAll(/\s+/g, ' ')
+      return {term: query, type: 'title'}
+    }
+    else throw error
```
Comment (dmijatovic) [inline frontend/components/software/edit/mentions/utils.ts:24]: I think this will break app. I am also not sure in which situation this code will be triggered. I would propose to assume title and return as such from function.

```Javascript
...
 } catch (error: any) {
    // remove double spaces:
    query = query.replaceAll(/\s+/g, ' ')
    return {term: query, type: 'title'}
}
```

**Review by dmijatovic — APPROVED** [review]
I have left remark in the issue #745 concerning the decision tree.

**Review by jmaassen — APPROVED** [review]
nice work!
